### PR TITLE
Use the local copy of a folder to start returning items before hitting t...

### PR DESCRIPTION
**Pull request by aleksclark**
...he API for improved

performance

pulled into separate PR per @bcoe

### CODE REVIEW

**Comment by rposborne** [comment]
@aleksclark OSS hero

**Comment by bcoe** [comment]
@aleksclark I'm a little bit worried about the complexity this introduces into pagination. For instance, when I'm done iterating over the local cache of files, and hit the API, will it return the same set of files we've already observed?

Long story short, I'd like to see some unit tests around this functionality, before I can pull it in. Perhaps you could capture some API responses from Box, and add to the file/folder/item specs? Specifically, I'd like to see tests around the behavior that occurs on the boundaries, when we move from pulling stuff in from the folder's items array, to pulling stuff in from the API.

**Comment by aleksclark** [comment]
@bcoe it won't, simply because it reuses the same pagination logic that
ensures we don't fetch the same page of items on subsequent requests using
'normal' pagination, but I'll add some tests ;)

On Mon, Dec 2, 2013 at 12:15 AM, Benjamin E. Coe
notifications@github.comwrote:

> @aleksclark https://github.com/aleksclark I'm a little bit worried
> about the complexity this introduces into pagination. For instance, when
> I'm done iterating over the local cache of files, and hit the API, will it
> return the same set of files we've already observed?
> 
> Long story short, I'd like to see some unit tests around this
> functionality, before I can pull it in. Perhaps you could capture some API
> responses from Box, and add to the file/folder/item specs? Specifically,
> I'd like to see tests around the behavior that occurs on the boundaries,
> when we move from pulling stuff in from the folder's items array, to
> pulling stuff in from the API.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/attachmentsme/ruby-box/pull/64#issuecomment-29596701
> .

## 

Aleks Clark
cell: 775-391-6114

**Comment by cburnette** [comment]
This seems like something that should be outside the core SDK.  Leave it up to a consumer to decide what to cache and for how long.

**Comment by aleksclark** [comment]
That makes sense to some extent, but currently the api as presented to the consumer will always hit the box api one more time, when in most cases the information they already need is already there. This is especially important in the case of web applications where the box connection isn't persisted and you have already paused your request for one roundtrip. If a refresh is truely needed, it could be done by re-fetching the folder item, but I think that in the context of a gem such as this, it's important to default to behaviour that will avoid hammering the API wherever possible _cough_ items by path _cough_

**Pull request closed without merging**
