### PR TITLE
Replace SSL 3 with TLS 1.2

### PR DESCRIPTION
**Pull request by filiptepper**
With SSL 3 POODLE issue (CVE 2014-3566) ssl_version set to :SSLv3 raises an exception:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure
```

With ssl_version set to :TLSv1_2 Box connection works as expected.

### CODE REVIEW

**Comment by andresbravog** [comment]
:+1:

**Comment by rafalyesware** [comment]
:+1:

**Comment by mike-yesware** [comment]
@filiptepper We've instead merged #106 to remove the explicit SSL version completely. Let me know if that isn't working for you in some way.

**Comment by filiptepper** [comment]
@mike-yesware Removing SSL version worked for me as well, thank you!

**Pull request closed without merging**
